# Generated by Django 4.0.6 on 2024-08-12 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=10)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('numero_celular', models.CharField(max_length=15)),
                ('foto_carnet', models.FileField(upload_to='fotos_carnet/')),
                ('hoja_vida_pdf', models.FileField(upload_to='hojas_vida/')),
            ],
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('numero_matricula', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('ano_creacion', models.IntegerField()),
                ('fotografia', models.FileField(upload_to='fotografias/')),
                ('piloto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.piloto')),
            ],
        ),
    ]
