services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn eRecuperacionDC.wsgi:application"
    plan: free
    port: 10000
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: eRecuperacionDC.settings
      - key: SECRET_KEY
        value: "your-secret-key"
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: "mydomain.com, www.mydomain.com"
